# Generated by Django 4.2.7 on 2023-11-16 14:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_profile_description'),
        ('user_site', '0002_alter_site_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficstatic',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_visit', models.JSONField(default=dict)),
                ('data_page', models.JSONField(default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.profile')),
            ],
        ),
    ]
