# Generated by Django 4.2.7 on 2023-11-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0006_trafficstatic_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficstatic',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
